### ISSUE TITLE
AsyncHTTPClient(force_instance=True) could cause memory leaks

### ISSUE THREAD

**Issue by 31z4** [gmr/tornado-aws#8]
What's the reason of forcing a new instance of the `AsyncHTTPClient`? The Tornado documentation states
> close() is generally only necessary when either the IOLoop is also being closed, or the force_instance=True argument was used when creating the AsyncHTTPClient

Not closing an `AsyncHTTPClient ` instance is potentially causing memory leaks.
And I see an evidence of this within my running Tornado application that uses `AsyncAWSClient` with `AsyncHTTPClient.configure('tornado.curl_httpclient.CurlAsyncHTTPClient')`

```
>>> import objgraph
>>> objgraph.show_most_common_types()
Curl                       393010
list                       33683
function                   23579
```
With 393010 `Curl` instances the proccess eats about 14GB of memory which is insane!

At the very least the `close` method of the `AsyncHTTPClient` must be exposed so that one could close it explicitly. Additionally `force_instance=True` could be removed if there was no particular reason for it.

**Comment by 31z4** [comment]
Looks like it's still leaking even after I added `with closing(AsyncAWSClient('sns')) as client` everywhere. Here is the picture of a 5 days old running process:
```
>>> import objgraph
>>> objgraph.show_most_common_types() 
Curl                953410
method              46870
dict                39688
```
Although, the process ate only 1GB memory, compared to 14GB without closing the client.

**Comment by gmr** [comment]
FWIW I do run this in production without issue, but I do not create a new instance on every request, instead assign a single instance to the application on startup. While I do see slow memory growth in my app, I've not taken the time to attribute it to this, though i wouldn't be surprised.

**Comment by 31z4** [comment]
@gmr having a single instance doesn't work for us due to [another issue](https://github.com/gmr/tornado-aws/issues/10) 😞

**Comment by gmr** [comment]
Added init option to disable force_instance in 1.2.0.
